name: Sync OSS to GitHub

on:
  schedule:
    - cron: '*/5 * * * *'  # 每小时运行一次
    workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        aws-region: cn-nanjing  # 替换为你的区域，例如 cn-hangzhou

    - name: Install OSS tools
      run: |
        pip install oss2

    - name: Sync files from OSS to local
      run: |
        python sync_oss.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Sync from OSS"
        git push